refresh_rate: 5 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} | {({l}):5.5} | {f}:{L} — {m}{n}"
  requests:
    kind: file
    path: "log/server.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} | {({l}):5.5} | {f}:{L} — {m}{n}"
root:
  level: debug
  appenders:
    - stdout
    # - requests
loggers:
  qtable:
    level: debug
    appenders:
      - requests
      - stdout
    additive: false

